### ISSUE TITLE
compilation error - device gemini

### ISSUE THREAD

**Issue by droidriz** [scotthartbti/android_hardware_qcom_display#1]
http://pastebin.com/FJ5zPbXs

**Comment by droidriz** [comment]
the temporary snippet fix.

**Comment by scotthartbti** [comment]
Yea I pushed a few more changes to the oneplus3 kernel and device... It
needs to compile with debugfs present.. Debugfs was removed in previous
commits.  Please pull the changes to revert disabling debugfs and it will
compile fine.

**Comment by scotthartbti** [comment]
Never mind I just saw your building for Gemini... Hmm... Try to cherry pick
these changes into your kernel

https://github.com/scotthartbti/android_kernel_oneplus_msm8996/commit/af2702b75ed664183875d6d80e78ad8fb27fdd06

https://github.com/scotthartbti/android_kernel_oneplus_msm8996/commit/04095d90ca6017d137ffcb4e0918931fd6580a01

It adds FRC debug support and should compile fine...  Please let me know if
you have any issues.

**Comment by droidriz** [comment]
yeah sure i will report back,thanks for quick response

**Comment by scotthartbti** [comment]
NP... Thanks.

**Comment by droidriz** [comment]
compiled successfully just reverted the lines used cyanogenmod's :)

**Comment by scotthartbti** [comment]
Yea you could do that as well... But I believe that cm will be pulling in
those changes here in the upcoming days, so at some point your device will
need the kernel side support to compile..  Just curious, were you able to
cherry pick the commits I sent you or did you not try?
